#!/bin/bash
set -e

ROOT=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

sudo systemctl stop wbds || true
sudo systemctl disable wbds || true

sed -i "/User/c\User=${USER}" $ROOT/wbds.service
sed -i "/ExecStart/c\ExecStart=${ROOT}/wbds" $ROOT/wbds.service

sudo cp $ROOT/wbds.service /etc/systemd/system/wbds.service

sudo systemctl start wbds
sudo systemctl enable wbds
