#!/bin/bash
set -e

ROOT=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
DATA=$HOME/.wbds
SYSTEM=/etc/systemd/system

cp $ROOT/wbds $DATA/wbds

sudo systemctl stop wbds || true
sudo systemctl disable wbds || true

sudo cp $ROOT/wbds.service $SYSTEM/wbds.service
sudo sed -i "/User/c\User=${USER}" $SYSTEM/wbds.service
sudo sed -i "/ExecStart/c\ExecStart=${DATA}/wbds" $SYSTEM/wbds.service

sudo systemctl start wbds
sudo systemctl enable wbds
